stages:
  - test
  - prerelease

image: mcr.microsoft.com/dotnet/core/sdk:2.2

tests:
  stage: test
  script: dotnet test AltwalkerExecutor.Tests/AltwalkerExecutor.Tests.csproj


dotnet pack:
  stage: prerelease
  script: dotnet pack AltwalkerExecutor
  artifacts:
    paths:
    - AltwalkerExecutor/bin/Debug/altwalker.executor.*.nupkg