name: Build

on:
  push:
    branches: ['develop', 'main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core SDK 3.1.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.x'

      - name: Build
        run: dotnet pack AltwalkerExecutor

      - name: Upload the build
        uses: actions/upload-artifact@v2
        with:
          name: 'dotnet-executor-build'
          path: 'AltwalkerExecutor/bin/Debug/AltWalker.Executor.*.nupkg'
