name: Tests

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Lint Code Base
        uses: super-linter/super-linter@v5
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET 3.1
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 3.1.x

      - name: Setup .NET 5
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 5.x

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x

      - name: Setup .NET 7
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Build
        run: |
          dotnet pack AltwalkerExecutor

      - name: Run tests
        run: |
          dotnet restore AltwalkerExecutor.Tests/AltwalkerExecutor.Tests.csproj
          dotnet build AltwalkerExecutor.Tests/AltwalkerExecutor.Tests.csproj
          dotnet test AltwalkerExecutor.Tests/AltwalkerExecutor.Tests.csproj

      - name: Upload log files
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: tests-logs
          path: '**/*.log'
